spring:
  datasource:
    url: jdbc:mysql://hopper.proxy.rlwy.net:56222/ChronoFlow?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: DoTKPrsSvsikuqxPhelmOIvCLNMcltyK
  data:
    redis:
      host: nozomi.proxy.rlwy.net
      port: 42775
      database: 0
      password: MmvxXZswsKgtFukcBGteMInEslKuMCTp

# log config
logging:
  level:
    nus.edu.u: debug
    org.springframework: warn
    com.zaxxer.hikari: debug

chronoflow:
  security:
    mock-enable: true
  captcha:
    enable: false
  cookie:
    http-only: false
    security: false
