spring:
  ##Production(use AWS Secrets Manager)
  #  config:
  #    import: aws-secretsmanager:ChronoFlowDBSecret
  #  datasource:
  #    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  #    username: ${DB_USER}
  #    password: ${DB_PASSWORD}
  #  data:
  #    redis:
  #      host: ${REDIS_HOST}
  #      port: ${REDIS_PORT}
  #      database: ${REDIS_DATABASE}
  #      password: ${REDIS_PASSWORD}

  datasource:
    url: jdbc:mysql://${PORD_DB_HOST}:${PORD_DB_PORT}/${PORD_DB_NAME}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${PORD_DB_USER}
    password: ${PORD_DB_PASSWORD}
  data:
    redis:
      host: ${PORD_REDIS_HOST}
      port: ${PORD_REDIS_PORT}
      database: ${PORD_REDIS_DATABASE}
      password: ${PORD_REDIS_PASSWORD}

# log config
logging:
  level:
    nus.edu.u: info
    org.springframework: error
    root: warn