spring:
  application:
    name: ChronoFLow
  devtools:
    restart:
      enabled: false
  # Data source
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    # Database connection pool
    hikari:
      # min free connection
      minimum-idle: 5
      # max connection
      maximum-pool-size: 20
      # free connection existence time
      idle-timeout: 300000
      # max lifetime of connection
      max-lifetime: 900000
      connection-timeout: 30000
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # Default is dev  Can modified by environment variable
  data:
    redis:
      repositories:
        enabled: false
  main:
    allow-circular-references: true
  # Servlet 配置
  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小

  # Jackson 配置项
  jackson:
    serialization:
      write-dates-as-timestamps: true # 设置 Date 的格式，使用时间戳
      write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
      write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
      fail-on-empty-beans: false # 允许序列化无属性的 Bean

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true            # db: user_name -> java: userName
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # dev-only SQL logs
  global-config:
    db-config:
      id-type: ASSIGN_ID     # snowflake-style; or AUTO for DB auto-increment
      table-underline: true

# 项目相关配置
chronoflow:
  name: ChronoFlow
  version: 1.0.0
  base-package: nus.edu.u
  captcha:
    enable: false
  security:
    token-header: Authentication
    token-parameter: token
    mock-enable: false
    mock-secret: mock_secret
    permit-all-urls:
      - /system/auth/login
      - /system/auth/refresh
      - /system/captcha/*
  cors:
    origins:
      - "http://172.20.10.9:5173"
      - "http://localhost:5173"
      - "https://chronoflow-frontend-production.up.railway.app"
  swagger:
    title: ChronoFLow Platform
    version: ${chronoflow.version}

server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8 # 必须设置 UTF-8，避免 WebFlux 流式返回（AI 场景）会乱码问题
      force: true

--- #################### API doc configuration ####################
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  default-flat-param-object: true

knife4j:
  enable: false
  setting:
    language: zh_cn


# log file address
logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log

# Jwt
jwt:
  secret: my-super-secret-key
  access-expire: 1800
  refresh-expire: 604800

# Captcha
aj:
  captcha:
    jigsaw: classpath:images/jigsaw # 滑动验证，底图路径，不配置将使用默认图片；以 classpath: 开头，取 resource 目录下路径
    pic-click: classpath:images/pic-click # 滑动验证，底图路径，不配置将使用默认图片；以 classpath: 开头，取 resource 目录下路径
    cache-type: redis # 缓存 local/redis...
    cache-number: 1000 # local 缓存的阈值,达到这个值，清除缓存
    timing-clear: 180 # local定时清除过期缓存(单位秒),设置为0代表不执行
    type: blockPuzzle # 验证码类型 default 三种都实例化。blockPuzzle 滑块拼图、clickWord 文字点选、pictureWord 文本输入
    water-mark: ChronoFlow # 右下角水印文字(我的水印)，可使用 https://tool.chinaz.com/tools/unicode.aspx 中文转 Unicode，Linux 可能需要转 unicode
    interference-options: 1 # 滑动干扰项(0/1/2)
    req-frequency-limit-enable: false # 接口请求次数一分钟限制是否开启 true|false
    req-get-lock-limit: 5 # 验证失败 5 次，get接口锁定
    req-get-lock-seconds: 10 # 验证失败后，锁定时间间隔
    req-get-minute-limit: 30 # get 接口一分钟内请求数限制
    req-check-minute-limit: 60 # check 接口一分钟内请求数限制
    req-verify-minute-limit: 60 # verify 接口一分钟内请求数限制