spring:
  #use environment variable
  datasource:
    url: jdbc:mysql://${TEST_DB_HOST}:${TEST_DB_PORT}/${TEST_DB_NAME}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${TEST_DB_USER}
    password: ${TEST_DB_PASSWORD}
  data:
    redis:
      host: ${TEST_REDIS_HOST}
      port: ${TEST_REDIS_PORT}
      database: ${TEST_REDIS_DATABASE}
      password: ${TEST_REDIS_PASSWORD}

# log config
logging:
  level:
    nus.edu.u: info
    org.springframework: warn