spring:
  application:
    name: ChronoFLow
  devtools:
    restart:
      enabled: false
  # Data source
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    # Database connection pool
    hikari:
      # min free connection
      minimum-idle: 5
      # max connection
      maximum-pool-size: 20
      # free connection existence time
      idle-timeout: 300000
      # max lifetime of connection
      max-lifetime: 900000
      connection-timeout: 30000
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test} # Default is dev  Can modified by environment variable
  data:
    redis:
      repositories:
        enabled: false
      lettuce:
        pool:
          # Maximum number of connections in the connection pool
          max-active: 200
          # The maximum blocking wait time of the connection pool (a negative value indicates no limit)
          max-wait: -1ms
          # Maximum idle connections in the connection pool
          max-idle: 10
          # Minimum number of idle connections in the connection pool
          min-idle: 0
  main:
    allow-circular-references: true
  # Servlet Config
  servlet:
    # File upload related configuration items
    multipart:
      max-file-size: 16MB # Single file size
      max-request-size: 32MB # Set the total uploaded file size

  # Jackson config
  jackson:
    serialization:
      write-dates-as-timestamps: true # Set the Date format to use a timestamp
      write-date-timestamps-as-nanoseconds: false
      write-durations-as-timestamps: true # Set the Duration format to use timestamp
      fail-on-empty-beans: false # Allow serialization of beans without attributes

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true            # db: user_name -> java: userName
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # dev-only SQL logs
  global-config:
    db-config:
      id-type: ASSIGN_ID     # snowflake-style; or AUTO for DB auto-increment
      table-underline: true

# Project config
chronoflow:
  name: ChronoFlow
  version: 1.0.0
  base-package: nus.edu.u
  security:
    refresh-token-expire: 604800
  swagger:
    title: ChronoFLow Platform
    version: ${chronoflow.version}

server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

--- #################### API doc configuration ####################
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  default-flat-param-object: true

knife4j:
  enable: false
  setting:
    language: zh_cn


# log file address
logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log

############## Sa-Token config (文档: https://sa-token.cc) ##############
sa-token:
  # token name
  token-name: Authorization
  # token validity period (unit: seconds) The default is 30 days, -1 means permanent validity
  timeout: 86400
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  # Minimum active frequency (unit: seconds). If the token does not access the system within this time,
  # it will be frozen. The default value of -1 means no limit and never freeze.
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  # Whether to allow multiple logins from the same account at the same time
  # (if true, multiple logins are allowed; if false, new logins will replace old logins)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  # When multiple people log into the same account, do they share a token?
  # (If true, all logins share a token; if false, a new token is created for each login.)
  is-share: true
  # Whether to output operation logs
  is-log: true
  # Jwt key
  jwt-secret-key: chronoflow123
  # Token style
  token-style: uuid
  cookie:
    http-only: true

management:
  endpoints:
    web:
      exposure:
        include: health,info    # 只暴露 health/info（安全）
      base-path: /actuator      # 默认就是 /actuator，可省略
  endpoint:
    health:
      show-details: never       # 生产环境建议 never；开发可用 always

email:
  from: no-reply@chronoflowse.xyz

notification:
  idempotency:
    email-prefix: "idem:email:"
    push-prefix: "idem:push:"
  email:
    rate-limit: 100        # max messages per window
    rate-window: 1m        # window size
    idempotency-ttl: 10m   # dedupe window
    rate-key: "rate:email:global"

aws:
  region: ${AWS_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

